// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7Ty__ev7Aw7IG_QIff1BcQE2bBGWps2k',
    appId: '1:343570716967:web:b32e743db9a98f32257102',
    messagingSenderId: '343570716967',
    projectId: 'citybus-live',
    authDomain: 'citybus-live.firebaseapp.com',
    storageBucket: 'citybus-live.firebasestorage.app',
    measurementId: 'G-BCW7MJMDSK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBspH2u_Iwb1WbwZqhHtci7AJYaO6wbmc',
    appId: '1:343570716967:android:00bdf46aeb3dcd28257102',
    messagingSenderId: '343570716967',
    projectId: 'citybus-live',
    storageBucket: 'citybus-live.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcB6wFJh2WZqtXPevI0xxkcU3d9hCQgNw',
    appId: '1:343570716967:ios:aabb2c6a899bafbb257102',
    messagingSenderId: '343570716967',
    projectId: 'citybus-live',
    storageBucket: 'citybus-live.firebasestorage.app',
    iosBundleId: 'com.citybus.citybusLive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcB6wFJh2WZqtXPevI0xxkcU3d9hCQgNw',
    appId: '1:343570716967:ios:aabb2c6a899bafbb257102',
    messagingSenderId: '343570716967',
    projectId: 'citybus-live',
    storageBucket: 'citybus-live.firebasestorage.app',
    iosBundleId: 'com.citybus.citybusLive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC7Ty__ev7Aw7IG_QIff1BcQE2bBGWps2k',
    appId: '1:343570716967:web:4229f6aec45a0ba0257102',
    messagingSenderId: '343570716967',
    projectId: 'citybus-live',
    authDomain: 'citybus-live.firebaseapp.com',
    storageBucket: 'citybus-live.firebasestorage.app',
    measurementId: 'G-5L5Z31FNPC',
  );
}
